# Generated by Django 5.2.6 on 2025-10-16 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_manage_blog", "Может управлять блогом")],
                "verbose_name": "Блоговая запись",
                "verbose_name_plural": "Блоговые записи",
            },
        ),
    ]
